//! Authentication: argon2id password verification, in-memory token store,
//! login rate limiting, and axum extractors that enforce permissions.
//!
//! Tokens are 32 random bytes generated by the OS CSPRNG. We hex-encode the
//! plaintext token in transport but only ever store its sha256 digest in
//! memory, so a heap dump cannot trivially be replayed against the server.
//! Token comparisons use [`subtle::ConstantTimeEq`] defensively even though
//! the map lookup is already keyed by the hash.

use crate::config::{Config, UserConfig};
use anyhow::{Result, anyhow};
use argon2::{
    Argon2, PasswordHash, PasswordHasher, PasswordVerifier,
    password_hash::{SaltString, rand_core::OsRng as ArgonRng},
};
use axum::{
    extract::{FromRef, FromRequestParts},
    http::{StatusCode, request::Parts},
};
use dashmap::DashMap;
use goldboot::registry::protocol::Permissions;
use governor::{Quota, RateLimiter, clock::DefaultClock, state::keyed::DefaultKeyedStateStore};
use rand::Rng;
use sha2::{Digest, Sha256};
use std::{
    net::IpAddr,
    num::NonZeroU32,
    sync::Arc,
    time::{SystemTime, UNIX_EPOCH},
};
use subtle::ConstantTimeEq;
use tracing::{debug, info, warn};

/// Hash a plaintext password using argon2id with the OS RNG for salt.
/// Output is in PHC string format, e.g.
/// `$argon2id$v=19$m=19456,t=2,p=1$<salt>$<hash>`.
pub fn hash_password(password: &str) -> Result<String> {
    let salt = SaltString::generate(&mut ArgonRng);
    let argon = Argon2::default();
    let hash = argon
        .hash_password(password.as_bytes(), &salt)
        .map_err(|e| anyhow!("argon2 hash: {e}"))?
        .to_string();
    Ok(hash)
}

/// Verify a plaintext password against a stored argon2 PHC hash.
/// Returns `Ok(true)` only on a valid match. All other cases return
/// `Ok(false)` — we never distinguish "no such user" from "wrong password"
/// in the response.
pub fn verify_password(password: &str, stored_phc: &str) -> bool {
    let parsed = match PasswordHash::new(stored_phc) {
        Ok(p) => p,
        Err(_) => return false,
    };
    Argon2::default()
        .verify_password(password.as_bytes(), &parsed)
        .is_ok()
}

/// Generate a fresh 32-byte token, hex-encoded for transport. Uses the
/// thread-local CSPRNG (ChaCha20 reseeded from the OS RNG).
pub fn new_token() -> String {
    let mut buf = [0u8; 32];
    rand::rng().fill_bytes(&mut buf);
    hex::encode(buf)
}

/// SHA256 of the plaintext token bytes. We store this in memory, never the
/// plaintext itself.
fn hash_token(plaintext: &str) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(plaintext.as_bytes());
    h.finalize().into()
}

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[derive(Clone)]
pub struct TokenRecord {
    pub username: String,
    pub permissions: Permissions,
    pub expires_at: u64,
}

/// In-memory token store keyed by sha256(token).
pub type TokenStore = Arc<DashMap<[u8; 32], TokenRecord>>;

pub fn new_token_store() -> TokenStore {
    Arc::new(DashMap::new())
}

/// Sweep expired tokens. Called periodically by the background task.
pub fn sweep_expired_tokens(store: &TokenStore) {
    let now = now_secs();
    store.retain(|_, rec| rec.expires_at > now);
}

/// Per-IP and per-username login rate limiters. Both must yield before a
/// login attempt proceeds. Failures count against the limiter; successes
/// do too (anti-credential-stuffing).
pub struct LoginLimiter {
    pub per_ip: RateLimiter<IpAddr, DefaultKeyedStateStore<IpAddr>, DefaultClock>,
    pub per_user: RateLimiter<String, DefaultKeyedStateStore<String>, DefaultClock>,
}

impl LoginLimiter {
    pub fn new() -> Self {
        let per_ip = RateLimiter::keyed(Quota::per_minute(
            NonZeroU32::new(20).expect("non-zero"),
        ));
        let per_user = RateLimiter::keyed(Quota::per_minute(
            NonZeroU32::new(5).expect("non-zero"),
        ));
        Self { per_ip, per_user }
    }

    pub fn check(&self, ip: IpAddr, username: &str) -> Result<(), &'static str> {
        if self.per_ip.check_key(&ip).is_err() {
            return Err("rate limit exceeded for source IP");
        }
        if self.per_user.check_key(&username.to_string()).is_err() {
            return Err("rate limit exceeded for user");
        }
        Ok(())
    }
}

impl Default for LoginLimiter {
    fn default() -> Self {
        Self::new()
    }
}

/// Issue a token for the given user after verifying credentials.
pub fn issue_token(
    config: &Config,
    store: &TokenStore,
    limiter: &LoginLimiter,
    remote_ip: IpAddr,
    username: &str,
    password: &str,
    ttl_secs: u64,
) -> Result<(String, TokenRecord), StatusCode> {
    if let Err(reason) = limiter.check(remote_ip, username) {
        warn!(
            event = "login.rate_limited",
            user = %username,
            ip = %remote_ip,
            reason
        );
        return Err(StatusCode::TOO_MANY_REQUESTS);
    }

    let user = config.users.get(username);
    // Compute argon2 even on missing user to keep timing roughly constant —
    // a real argon2 check dominates the latency budget.
    let verified = match user {
        Some(u) => verify_password(password, &u.password_hash),
        None => {
            let _ = verify_password(password, DUMMY_HASH);
            false
        }
    };
    if !verified {
        info!(
            event = "login.fail",
            user = %username,
            ip = %remote_ip,
        );
        return Err(StatusCode::UNAUTHORIZED);
    }
    let u: &UserConfig = user.expect("verified user must exist");

    let token = new_token();
    let key = hash_token(&token);
    let record = TokenRecord {
        username: username.to_string(),
        permissions: Permissions {
            pull: u.pull,
            push: u.push,
        },
        expires_at: now_secs() + ttl_secs,
    };
    store.insert(key, record.clone());
    info!(event = "login.ok", user = %username, ip = %remote_ip);
    Ok((token, record))
}

/// Pre-baked argon2 PHC of a random value, used to keep verify timing
/// constant when the username does not exist. Generated once at compile
/// time would be ideal, but for now we use a hand-computed value with the
/// crate defaults (m=19456, t=2, p=1). If the argon2 crate ever upgrades
/// its defaults this string can be regenerated with `cargo run -- user hash`.
const DUMMY_HASH: &str = "$argon2id$v=19$m=19456,t=2,p=1$YQAAAAAAAAAAAAAAAAAAAA$0r/W2/dXqAvjVcg0nKKM2tn3wkvMOJjXAg8DZpwIPng";

// ── Extractors ──────────────────────────────────────────────────────────────

#[derive(Clone)]
pub struct AppState {
    pub config: Arc<Config>,
    pub tokens: TokenStore,
    pub limiter: Arc<LoginLimiter>,
}

impl FromRef<AppState> for Arc<Config> {
    fn from_ref(input: &AppState) -> Self {
        input.config.clone()
    }
}

/// Extractor that resolves and validates the bearer token. Returns 401
/// without any indication of why the request was rejected.
pub struct AuthenticatedUser {
    pub username: String,
    pub permissions: Permissions,
}

impl<S> FromRequestParts<S> for AuthenticatedUser
where
    AppState: FromRef<S>,
    S: Send + Sync,
{
    type Rejection = StatusCode;

    async fn from_request_parts(parts: &mut Parts, state: &S) -> Result<Self, Self::Rejection> {
        let state = AppState::from_ref(state);
        let auth = parts
            .headers
            .get(axum::http::header::AUTHORIZATION)
            .and_then(|v| v.to_str().ok())
            .ok_or(StatusCode::UNAUTHORIZED)?;
        let token = auth
            .strip_prefix("Bearer ")
            .ok_or(StatusCode::UNAUTHORIZED)?
            .trim();
        if token.is_empty() {
            return Err(StatusCode::UNAUTHORIZED);
        }
        let key = hash_token(token);
        let record = state
            .tokens
            .get(&key)
            .ok_or(StatusCode::UNAUTHORIZED)?
            .clone();
        // Constant-time check — defence in depth. The DashMap lookup is
        // already by the hash so this can only differ if there's a hash
        // collision (cryptographically negligible for SHA256).
        let stored_key = *state.tokens.get(&key).map(|r| r.key().clone()).as_ref().unwrap_or(&[0u8; 32]);
        if key.ct_eq(&stored_key).unwrap_u8() != 1 {
            return Err(StatusCode::UNAUTHORIZED);
        }
        if record.expires_at <= now_secs() {
            state.tokens.remove(&key);
            return Err(StatusCode::UNAUTHORIZED);
        }
        debug!(user = %record.username, "authenticated");
        Ok(Self {
            username: record.username,
            permissions: record.permissions,
        })
    }
}

/// Wrapper enforcing the pull permission. Returns 403 (NOT 401) on a
/// successfully authenticated but unprivileged user.
pub struct PullPermission(pub AuthenticatedUser);

impl<S> FromRequestParts<S> for PullPermission
where
    AppState: FromRef<S>,
    S: Send + Sync,
{
    type Rejection = StatusCode;

    async fn from_request_parts(parts: &mut Parts, state: &S) -> Result<Self, Self::Rejection> {
        let user = AuthenticatedUser::from_request_parts(parts, state).await?;
        if !user.permissions.pull {
            return Err(StatusCode::FORBIDDEN);
        }
        Ok(Self(user))
    }
}

/// Wrapper enforcing the push permission.
pub struct PushPermission(pub AuthenticatedUser);

impl<S> FromRequestParts<S> for PushPermission
where
    AppState: FromRef<S>,
    S: Send + Sync,
{
    type Rejection = StatusCode;

    async fn from_request_parts(parts: &mut Parts, state: &S) -> Result<Self, Self::Rejection> {
        let user = AuthenticatedUser::from_request_parts(parts, state).await?;
        if !user.permissions.push {
            return Err(StatusCode::FORBIDDEN);
        }
        Ok(Self(user))
    }
}

/// Revoke (i.e. delete) the token presented in the Authorization header.
pub fn revoke_token(store: &TokenStore, token: &str) {
    let key = hash_token(token);
    store.remove(&key);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn argon2_round_trip() {
        let phc = hash_password("hunter2").unwrap();
        assert!(verify_password("hunter2", &phc));
        assert!(!verify_password("wrong", &phc));
    }

    #[test]
    fn token_store_lookup_and_expiry() {
        let store = new_token_store();
        let token = new_token();
        store.insert(
            hash_token(&token),
            TokenRecord {
                username: "alice".into(),
                permissions: Permissions {
                    pull: true,
                    push: false,
                },
                expires_at: now_secs() + 60,
            },
        );
        assert!(store.contains_key(&hash_token(&token)));

        // Now insert an expired record and sweep it
        store.insert(
            hash_token("expired"),
            TokenRecord {
                username: "bob".into(),
                permissions: Permissions::default(),
                expires_at: 1,
            },
        );
        sweep_expired_tokens(&store);
        assert!(!store.contains_key(&hash_token("expired")));
        assert!(store.contains_key(&hash_token(&token)));
    }

    #[test]
    fn dummy_hash_is_valid_argon2() {
        // verify_password must run successfully (returning false) against
        // DUMMY_HASH so the username-not-found code path has constant time.
        assert!(!verify_password("anything", DUMMY_HASH));
    }
}
